apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: policy
spec:
  targets:
    - name: my-ws
  origins:
    - jwt:
        issuer: "testing@secure.istio.io"
        jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.3/security/tools/jwt/samples/jwks.json"
  principalBinding: USE_ORIGIN
