apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: service-role
  namespace: test-istio
spec:
  rules:
    - services: ["*"]
      methods: ["GET"]
      constraints:
        - key: "destination.labels[app.kubernetes.io/name]"
          values: ["simple-web-server"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: service-role-binding
  namespace: test-istio
spec:
  subjects:
    - properties:
        source.namespace: "istio-system"
  roleRef:
    kind: ServiceRole
    name: "service-role"
