apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-service
spec:
  hosts:
    - "www.test.com"
  gateways:
    - gateway
  http:
    - route:
      - destination:
          host: my-ws
          port:
            number: 8080
